name: dartbeans
version: 0.1.0
author: Roberto Tassi <roberto.tassi@fromlabs.org>
description: DartBeans is a Dart library that helps working with event streams.
homepage: https://github.com/fromlabs/dartbeans
dev_dependencies:
  unittest: '>=0.8.5 <0.9.0'
